name: Epic
description: Large initiative grouping related features and tasks
title: "[Epic] "
labels: ["epic"]
type: epic

body:
  - type: textarea
    id: content
    attributes:
      label: Description
      value: |
        ## Что делаем
        ...

        ## Цель
        ...

        ## Входит в scope
        - ...

        ## Не входит в scope
        - ...

        ## Готово, если:
        - [ ] ...
        - [ ] ...
        - [ ] ...

    validations:
      required: true