name: Feature
description: Product feature or meaningful functionality
title: "[Feature] "
type: feature

body:
  - type: textarea
    id: content
    attributes:
      label: Description
      value: |
        ## Что делаем
        ...

        ## Зачем
        ...

        ## Готово, если:
        - [ ] ...
        - [ ] ...
        - [ ] ...

        ## Ограничения / зависимости
        - ...

        ## Ссылки
        - Design:
        - Spec:
    validations:
      required: true